
package soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileStorageServiceMsg", targetNamespace = "http://soap.web/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileStorageService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws SoapServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFile", targetNamespace = "http://soap.web/", className = "web.soap.AddFile")
    @ResponseWrapper(localName = "addFileResponse", targetNamespace = "http://soap.web/", className = "web.soap.AddFileResponse")
    public boolean addFile(
        @WebParam(name = "arg0", targetNamespace = "")
        UserFile arg0)
        throws SoapServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns web.soap.UserFile
     * @throws SoapServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFile", targetNamespace = "http://soap.web/", className = "web.soap.GetFile")
    @ResponseWrapper(localName = "getFileResponse", targetNamespace = "http://soap.web/", className = "web.soap.GetFileResponse")
    public UserFile getFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws SoapServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws SoapServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeFile", targetNamespace = "http://soap.web/", className = "web.soap.RemoveFile")
    @ResponseWrapper(localName = "removeFileResponse", targetNamespace = "http://soap.web/", className = "web.soap.RemoveFileResponse")
    public boolean removeFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws SoapServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<web.soap.UserFile>
     * @throws SoapServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOneTypeFileList", targetNamespace = "http://soap.web/", className = "web.soap.GetOneTypeFileList")
    @ResponseWrapper(localName = "getOneTypeFileListResponse", targetNamespace = "http://soap.web/", className = "web.soap.GetOneTypeFileListResponse")
    public List<UserFile> getOneTypeFileList(
        @WebParam(name = "arg0", targetNamespace = "")
        Type arg0)
        throws SoapServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<web.soap.UserFile>
     * @throws SoapServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllFiles", targetNamespace = "http://soap.web/", className = "web.soap.GetAllFiles")
    @ResponseWrapper(localName = "getAllFilesResponse", targetNamespace = "http://soap.web/", className = "web.soap.GetAllFilesResponse")
    public List<UserFile> getAllFiles()
        throws SoapServiceException_Exception
    ;

}
